# Generated by Django 4.1.7 on 2024-09-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField()),
                ('contact_information', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='company_logos/')),
            ],
        ),
    ]
