# Generated by Django 4.1.7 on 2024-09-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
