# Generated by Django 4.1.7 on 2024-09-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0007_customeruser_is_admin_customeruser_is_employee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
