# Generated by Django 4.1.7 on 2024-09-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0022_alter_employee_department_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
