# Generated by Django 4.1.7 on 2024-09-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0025_alter_department_company_alter_role_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
