# Generated by Django 4.1.7 on 2024-09-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0027_alter_department_name_alter_role_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Departments',
        ),
    ]
