# Generated by Django 4.1.7 on 2024-09-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('companyapp', '0028_rename_department_departments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cutomerUser',
            new_name='CustomerUser',
        ),
    ]
