# Generated by Django 4.1.7 on 2024-09-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0030_departments_user_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='company',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
