# Generated by Django 4.1.7 on 2024-09-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0032_alter_employee_user_alter_hr_manger_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
